INSERT INTO product (name, created_at, updated_at) VALUES
        ('Lait', NOW(), NOW()),
        ('Pain', NOW(), NOW()),
        ('Beurre', NOW(), NOW()),
        ('Oeufs', NOW(), NOW()),
        ('Fromage', NOW(), NOW()),
        ('Jambon', NOW(), NOW()),
        ('Poulet', NOW(), NOW()),
        ('Pâtes', NOW(), NOW()),
        ('Riz', NOW(), NOW()),
        ('Pommes de terre', NOW(), NOW()),
        ('Tomates', NOW(), NOW()),
        ('Salade', NOW(), NOW()),
        ('Carottes', NOW(), NOW()),
        ('Pommes', NOW(), NOW()),
        ('Bananes', NOW(), NOW()),
        ('Yaourts', NOW(), NOW()),
        ('Céréales', NOW(), NOW()),
        ('Jus d’orange', NOW(), NOW()),
        ('Eau minérale', NOW(), NOW()),
        ('Café', NOW(), NOW());